app = 'letsraid'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[processes]
  bot = "uv run python bot.py"

[env]
  DB_PATH = '/data/letsraid.db'
  HIDDEN_VC = '1465694444484427903:1467219468877828227'

[mounts]
  source = "letsraid_data"
  destination = "/data"
  processes = ["bot"]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
  processes = ["bot"]
